### PR TITLE
Trend tab

### PR DESCRIPTION
**Pull request by callid01**
Hi @vaelliott,

Here's the trend tab for review, Abbie copied the changes over to a new branch so there's no conflicts. 

The only thing I can't get quite right is the confidence intervals as at the moment they're different colours to the line series. You can link the arearange series to the line series by using "linked_to" but I couldn't get it working, so would be great if you didn't mind having a look?

Thanks!

### CODE REVIEW

**Comment by vaelliott** [comment]
Hi calli - its almost there! I'm just dragging monica into this review as I think I need her help & superior skills. I think using the 'linkedto' to apply same colour scheme to the CI means we need to get a bit more sophisticated  as there are multiple data series of differing lengths which i think is perhaps why the 'linkedto =previous' is failing.  
I am also finding the rendering of the page a little slow - maybe that is just because there are so many dropdown filters. Speaking of which I wonder if there is anything we could do to reduce the length of the options/filters in sidepanel?  For example could the confidence interval on/off and numerator/rate options be within a popover?
When i save the chart i also get a chart with a black background which i'm assuming can be changed somewhere?

**Comment by monicamcgibbon** [comment]
Hi everyone, 

I’ve done a tidy up of this PR – it probably looks like I’ve changed a lot but it’s mostly re-organising all the great work @abigap01  and @callid01  have already done 😊 e.g. where things sit in the UI, streamlining a bit of the server code and adding more comments to things. 

Main changes:

-	Organised the sidebar using an accordion – not sure how people feel about this but thought it might help keep things tidy since this sidebar is the busiest sidebar in the app (will look more organised on a mobile too)? I’ve only got the indicator filter open by default at the moment but all/some of the panels can be opened if you change the accordion settings, if we want to keep the accordion.

-	Reduced the number of reactive dataframes – instead of creating one for scotland, one for the main selected geography and one of the additional geography filters, I’ve just moved the logic from those 3  into 1 big dataframe which will filter for all those things. This means there’s now less series being added to the chart which should solve any issues with confidence intervals as theres now 1 series for the lines, and 1 series for the Cis

-	Other  small changes like Moving the chart titles outside of the chart to match how we’ve done it elsewhere in the app (when this branch becomes up to date with master the main chart title will appear bold)

-	Added a data table so users can toggle between chart and data

-	Temporarily removed the highchart theme Calli made, not because I don’t think we should have one but because some elements of it weren’t being used. Would maybe be good to revisit this and apply it to all the charts in the app at the end? Using the phs colours for the lines now but there's still an issue with the colours not matching up to the confidence intervals as they do in the current profiles tool - need to revisit this as it looks really weird at the moment if you add lots of areas!

If anyone has any questions about what I’ve done give me a shout, or @vaelliott  if you have any suggested changes I'm sure Abbie can pick them up?

**Comment by monicamcgibbon** [comment]
Think the issue with confidence interval colours not matching the line should now be resolved!

**Comment by vaelliott** [comment]
Thanks for changes monica - i've mentioned that maybe we remove the 1st accordion box (moving definitions button to underneath the filter and the help to a panel within the navcard) which i think abbie is maybe going to work on before merging? Other than that i think its ready to merge.
Theres also some work to be done on the actual columns/column names that are returned when you select data download but that applies to all tabs and is maybe easier to look at in a separate branch

**Review by vaelliott — APPROVED** [review]

**Pull request merged**
