### PR TITLE
ER Combining deprivation and popgroup tabs

### PR DESCRIPTION
**Pull request by elizabeth-richardson**
Contains the data prep script and changes to the popgroup tab so that SIMD can be included as a possible split, when available, and a second split filter (e.g. sex) can be selected if this is available. The specifics of the new data format required are noted in the script combine_popgroup_and_simd_data.R, which should be run before running the app from this branch. 

If this branch is OK it would mean the deprivation tab could be removed, and new plots for RII, SII and PAR could be added to the popgroup tab (conditional on SIMD being selected as a split)

### CODE REVIEW

**Comment by elizabeth-richardson** [comment]
Correction: the data prep file I have included here - update_popgroup_data_new.R is not needed and can be deleted. Better to just add a sex column to the _ineq.rds files being read in (as in the case of the mental health data I've put in the "Test Shiny Data" folder (amhi_ineq.rds)), or add a sex="Total" column if one doesn't exist after reading in (this is done in the new processing file combine_popgroup_and_simd_data.R). I've added sex as a grouping column in the update_deprivation_data.R file, so it now copes with input files with or without a sex column. Once that has been run the new file combine_popgroup_and_simd_data.R takes the two files resulting from reading in the popgroup data and the deprivation data and does the necessary tweaks to combine them ready for the combined popgroups tab.

**Comment by elizabeth-richardson** [comment]
Notes on the format of the new popgroups data file (popgroup_dataset_new.parquet), copied from the data prep script:

# split_name is the same: this populates the first split filter "Select population split"
# split_names have been standardised throughout. 
# Current options: "Age", "Income (Equivalised)", "Long-term conditions", "Sex", "Deprivation (SIMD)", "Urban/Rural". 
# Any rows with split_name=="Total" should be dropped.
# Deprivation should always be in split_name rather than split_value2, because its data needs to be treated differently.
# This means the other splits can be in either column, depending on whether also combined with SIMD or not.

# split_value2 = new variable, populates the second split filter "Select 2nd population split:"
# Current values for split_value2 are "Male", "Female", "Total". 
# split_value2 should be NA if the data relate to a single split

# split_values are what are displayed in the charts, and require some format standardising:
# ages e.g., "0 to 4 years", "60+ years", "Children", "Working-age adults", "Pensioners" (latter 3 could do with age ranges being given too) 
# income: "1 - highest income" to "5 - lowest income"
# Long-term conditions: "No", "Yes, but not limiting", "Yes, limiting"
# Sex: Female, Male, Total 
# SIMD: "1 - most deprived" to "5 - least deprived", Total
# Urb/Rural: "1 Large urban areas" to "6 Remote rural"
# split_value == "Total" is what is used to plot the average on the charts, if selected. 
# split_value == "Total" will currently need to be repeated in the data for each split_name (and split2_filter, if used), unless this can be included in the data prep
# I have extracted Totals for each def_period x code x ind_id without a split_value==Total (from main_dataset) and appended to the popgroup data to give averages.

# quint_type has been assumed to be scotland unless specified. 
# Check this assumption is correct. Applies to HWB and CWB profiles only (when SIMD data were included in the popgroups file rather than the deprivation file)

**Comment by monicamcgibbon** [comment]
I'm having some issues with the data prep script. The function to update pop groups won't work because some of the files have an extra column (indicator name), so it won't combine the files. I don't think this column is supposed to be there as it's attached at some point in the process when other fields from the technical document are joined to the dataset.

**Comment by monicamcgibbon** [comment]
Just wondering if we should also amend the function to create the deprivation dataset so that it doesn't save the file in the shiny data folder if we won't need to read it in to the app? The pop groups and deprivation dataset could then just be combined using the versions prepared and saved in the global environment instead or reading them back in and then having to delete the deprivation one?

**Comment by elizabeth-richardson** [comment]
> Just wondering if we should also amend the function to create the deprivation dataset so that it doesn't save the file in the shiny data folder if we won't need to read it in to the app? The pop groups and deprivation dataset could then just be combined using the versions prepared and saved in the global environment instead or reading them back in and then having to delete the deprivation one?

Good idea!

**Comment by elizabeth-richardson** [comment]
@monicamcgibbon There are a few edits I need to make to this PR, including those you've noted. Shall I scrap it, and work more on the branch and submit a new PR?

**Comment by monicamcgibbon** [comment]
Yeah you could do if there's more that needs changed and we can pick it back up again when ready to review. The actual new pop groups tab itself is working well at my end and looking good though!

**Comment by elizabeth-richardson** [comment]
OK, will do that and hopefully resubmit it today

**Comment by elizabeth-richardson** [comment]
Found that this additional column is in 5 (at least) CWB _shiny_popgroup.csv files that were added last week. I don't want to go in and manually edit these files as they're not mine. What to do?


Elizabeth Richardson | Public Health Intelligence Adviser

Public Health Scotland

Email: ***@***.******@***.***>

[Public Health Scotland logo]

Web<http://www.publichealthscotland.scot/> | Twitter<https://twitter.com/P_H_S_Official> | Instagram<https://www.instagram.com/publichealthscotland/>



________________________________

**Comment by monicamcgibbon** [comment]
I reckon we can manually delete the rogue column from the files for now (maybe just save backups of them somewhere) and we can take note of the 5 indicators because the actual R scripts to produce those indicator files will need amended to remove the column before the csv files are saved.

**Comment by elizabeth-richardson** [comment]
[like]  Elizabeth Richardson reacted to your message:
________________________________

**Comment by elizabeth-richardson** [comment]
I've copied the 5 CWB indicator files to a new folder here
D:\Profiles\Data\Test Shiny Data\orig_CWB_popgroup_files
Indicators are 99116, 99117, 99118, 99121 and 99123.
I've deleted the extra column from the csv files and the update_popgroup script now works.
🙂



Elizabeth Richardson | Public Health Intelligence Adviser

Public Health Scotland

Email: ***@***.******@***.***>

[Public Health Scotland logo]

Web<http://www.publichealthscotland.scot/> | Twitter<https://twitter.com/P_H_S_Official> | Instagram<https://www.instagram.com/publichealthscotland/>



________________________________

**Pull request closed without merging**
