### PR TITLE
Ve front page

### PR DESCRIPTION
**Pull request by vaelliott**
I've made some tweaks to the landing page - adding back in the whats new box with some slightly random blurb about the redesign and the mental health profile. I might still tweak the exact text but I want to just slot that back in.
Theres also a small change in the pop group module to ensure that the split type drop down menu always sorts the options alphabetically.

### CODE REVIEW

**Comment by vaelliott** [comment]
I should have mentioned i've also reorder the profiles boxes on the front page to bring the mental health profile closer to the top and push some of our more out dated profiles down to the bottom.

**Comment by monicamcgibbon** [comment]
@vaelliott all looks good, just added the what's new text into a bslib card so it has same style as rest of app and made sure the profile names are now centered in the profile cards on landing page because some with long names looked off before. Hope that's okay!

**Comment by vaelliott** [comment]
Looks great thanks - i think this branch can be merged unless you are using it to reintroduce the logo too?

**Comment by monicamcgibbon** [comment]
I've just started a new branch for small tweaks like adding logo, tooltips, button style etc. so will just get this one merged now.

**Pull request merged**
